name = "movie-melody-mixer"
compatibility_date = "2024-07-10"

# Configuration for local development
[env.development]
compatibility_date = "2024-07-10"

# KV bindings for sessions (if needed)
# [[kv_namespaces]]
# binding = "SESSION"
# id = "your-kv-namespace-id" 